name: Build and deploy Docker app with Azure SQL Backend to Azure Web App on Containers

on: push

# Pre-Requisites
# Create the target Resource Group
# 1. Open the Azure Cloud Shell at https://shell.azure.com. You can alternately use the Azure CLI if you've installed it locally. (For more information on Cloud Shell, see the Cloud Shell Overview.)  
#   az group create --name {resource-group-name} --location {resource-group-location}
# 
# 2. Create a Service Principal to manage your resource group from GitHub Actions
#   az ad sp create-for-rbac --name "{service-principal-name}" --sdk-auth --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group-name}  
#
# For help, go to: https://github.com/Azure/login#configure-deployment-credentials



# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, DB_ADMIN_LOGIN_PASSWORD
# 2. Change these variables for your configuration:
env:
  APP_NAME: todo-sample  # set this to your application's name
  APP_ENVIRONMENT: dev   # environment to setup the resource. Allowed vaules: dev, qa, pro
  APP_LOCATION_SHORT: weu  # location, be sure it represent a shortern for the {resource-group-location} used in the pre-requistes
  DB_NAME: todosDb  # database name used by the application
  DB_ADMIN_LOGIN: dbadminlogin  # name for the database admin login
  DB_ADMIN_LOGIN_PASSWORD: ${{ secrets.DB_ADMIN_LOGIN_PASSWORD }}  # password for the db admin login
  AZURE_RESOURCE_GROUP: rsg-todo-sample  # target resource group {resource-group-name} you setup in the pre-requisties

jobs:
  deploy_environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ralarcon/reference-architectures ## TODO: Point to the official reference-architectures repo
        ref: containerized-web-app ## TODO: Remove branch reference once published
        path: reference-architectures
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: reference-architectures/managed-web-app/containerized-web-app/PaaS-Containerized/Templates/PaaS-Containerized.json
        parameters: appName=${{ env.APP_NAME }};environment=${{ env.APP_ENVIRONMENT }};locationShort=${{ env.APP_LOCATION_SHORT }};dbName=${{ env.DB_NAME }};dbAdminLogin=${{ env.DB_ADMIN_LOGIN }};dbAdminLoginPassword=${{ env.DB_ADMIN_LOGIN_PASSWORD }}
        deploymentName: github-action-enviroment-deployment